name: 'Hello World'
description: 'Greet someone'

inputs:
  username: # id of input
    description: 'username'
    required: true
    default: 'zunnorain'

runs:
  using: "composite"
  steps:
    - name: Golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.8'
      env:
        GO111MODULE: on
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: zunnorainzaheer/new-action
    - shell: bash
      run: go run main.go ${{ inputs.username }} ${{ inputs.username }}
