name: 'Hello World'
description: 'Greet someone'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: Golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.8'
    - run: go run main.go