name: 'Hello World'
description: 'Greet someone'

inputs:
  username:  # id of input
    description: 'username'
    required: true
    default: 'zunnorain'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Golang
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.8'
    - shell: bash
      run: go run ${{ github.action_path }}/main.go
      env:
        NAME: "${{ inputs.username }}"
